apiVersion: v1
kind: Service
metadata:
    name: k8s-demo-svc
    labels:
        app: k8s-demo
spec:
    type: NodePort
    ports:
        - port: 80
          nodePort: 30050
    selector:
        app: k8s-demo
